version: '3'
services:
  server:
    build:
      context: ./src/server
    ports:
      - "5000:5000"
    volumes:
      - ./src/server:/app
    depends_on:
      - mongo

  website:
    build:
      context: ./src/website
    ports:
      - "80:80"
    volumes:
      - ./src/website/static:/usr/share/nginx/html/static
      - ./src/website/templates:/usr/share/nginx/html/templates
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db  # Mount the data directory for MongoDB
